# Generated by Django 5.1 on 2024-08-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
