# Generated by Django 5.1 on 2024-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_messages', '0002_alter_emailmessage_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
