# Generated by Django 5.1 on 2024-08-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_messages', '0003_alter_emailmessage_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
